"""Backend-switching tests: DemoClient + the BACKEND_DISPATCH / ALGORITHM_DISPATCH tables.

Covers:
  - DemoClient constructs against either backend (Ollama or vLLM)
  - BACKEND_DISPATCH produces the right type per key
  - ALGORITHM_DISPATCH maps each algorithm name to the right processor class
  - mid-session swap: closing a vLLM backend then re-loading does not leak
    state from the previous instance

Most assertions are cheap and run without GPU (we mock the vLLM engine where
needed). Only the real-load swap test is marked slow+gpu.
"""

from __future__ import annotations

import asyncio
import os
import warnings
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from soundcode.code import Category, Diagnostic
from soundcode.llm import GenerationConfig, LlmServer, OrchestrationMode, Token
from soundcode.logits_processors import (
    NoopLogitsProcessor,
    RocodeDecayingPenaltyProcessor,
    SemGuardEvaluatorProcessor,
)
from soundcode.web.demo_client import DemoClient, DemoConfig


# ─── GPU gating ───────────────────────────────────────────────────────


def _gpu_tests_enabled() -> bool:
    return os.environ.get("RUN_GPU_TESTS", "") == "1"


gpu_required = pytest.mark.skipif(
    not _gpu_tests_enabled(),
    reason="set RUN_GPU_TESTS=1 to run GPU-bound backend-switching tests",
)


TEST_MODEL = os.environ.get(
    "SOUNDCODE_VLLM_TEST_MODEL",
    "Qwen/Qwen2.5-Coder-7B-Instruct",
)


# ─── shared fakes ─────────────────────────────────────────────────────


class _FakeChecker:
    """Minimal checker that returns no diagnostics — DemoClient only needs
    something with an async `.check(source) -> list[Diagnostic]`."""

    async def check(self, source: str) -> list:
        return []


class _FakeBoundary:
    """Boundary detector that never reports a boundary — short-circuits the
    in-loop verifier path so DemoClient construction tests don't need a
    real workspace."""

    def find_boundaries(self, content: str) -> list:
        return []


# ─── test_demo_client_accepts_ollama_backend ───────────────────────────


def test_demo_client_accepts_ollama_backend():
    """DemoClient must construct cleanly with a real LlmServer (Ollama) as
    the backend. We pass `mistral:7b` as a stand-in model — no network
    traffic is generated by the constructor."""
    llm = LlmServer(model="mistral:7b")
    demo = DemoClient(
        llm=llm,
        checker=_FakeChecker(),
        config=DemoConfig(token_delay_s=0, repetition_window=0,
                          wall_budget_s=5),
        emit=lambda ev: asyncio.sleep(0),
    )
    assert demo.llm is llm
    assert isinstance(demo.llm, LlmServer)
    # `llm.config` must be present and a GenerationConfig — DemoClient reads
    # `.mode` off it on every generate().
    assert isinstance(demo.llm.config, GenerationConfig)


# ─── test_demo_client_accepts_vllm_backend ─────────────────────────────


def test_demo_client_accepts_vllm_backend():
    """DemoClient must construct cleanly with a VllmBackend (real instance,
    but the engine is never built — warmup() is lazy)."""
    from soundcode.vllm_backend import VllmBackend

    backend = VllmBackend(
        model="dummy",  # never loaded — warmup() not called
        config=GenerationConfig(),
    )
    demo = DemoClient(
        llm=backend,
        checker=_FakeChecker(),
        config=DemoConfig(token_delay_s=0, repetition_window=0,
                          wall_budget_s=5),
        emit=lambda ev: asyncio.sleep(0),
    )
    assert demo.llm is backend
    assert isinstance(demo.llm.config, GenerationConfig)
    # think_budget_exceeded is a getattr-read in DemoClient — must be present
    # and False on the vLLM backend.
    assert hasattr(demo.llm, "think_budget_exceeded")
    assert demo.llm.think_budget_exceeded is False


# ─── test_backend_dispatch_returns_correct_class_per_request ───────────


def test_backend_dispatch_returns_correct_class_per_request():
    """BACKEND_DISPATCH["ollama"] → LlmServer; BACKEND_DISPATCH["vllm"] →
    VllmBackend; unknown key → KeyError (the server normalises before
    dispatch, but a direct lookup must fail loudly)."""
    from soundcode.web.server import BACKEND_DISPATCH
    from soundcode.vllm_backend import VllmBackend

    cfg = GenerationConfig()
    proc = NoopLogitsProcessor()

    ollama = BACKEND_DISPATCH["ollama"]("mistral:7b", cfg, proc)
    assert isinstance(ollama, LlmServer)
    # Ollama path discards the processor — it has no logits hook.
    # We don't assert on the discarded reference here, just confirm the
    # returned object is the expected type.

    vllm = BACKEND_DISPATCH["vllm"](TEST_MODEL, cfg, proc)
    assert isinstance(vllm, VllmBackend)
    # vLLM path must thread the processor through.
    assert vllm.logits_processor is proc

    # Unknown key raises KeyError on direct lookup.
    with pytest.raises(KeyError):
        BACKEND_DISPATCH["unknown_backend"]("x", cfg, proc)


# ─── test_algorithm_dispatch_returns_correct_processor ─────────────────


def test_algorithm_dispatch_returns_correct_processor():
    """ALGORITHM_DISPATCH must map each algorithm name to the right class:
        soundcode → NoopLogitsProcessor
        rocode    → RocodeDecayingPenaltyProcessor
        semguard  → SemGuardEvaluatorProcessor
    All three nullary-constructible."""
    from soundcode.web.server import ALGORITHM_DISPATCH

    assert ALGORITHM_DISPATCH["soundcode"] is NoopLogitsProcessor
    assert ALGORITHM_DISPATCH["rocode"] is RocodeDecayingPenaltyProcessor
    assert ALGORITHM_DISPATCH["semguard"] is SemGuardEvaluatorProcessor

    # Nullary construction must succeed for each.
    assert isinstance(ALGORITHM_DISPATCH["soundcode"](),
                      NoopLogitsProcessor)
    assert isinstance(ALGORITHM_DISPATCH["rocode"](),
                      RocodeDecayingPenaltyProcessor)
    # SemGuard emits a warning at construction when no ckpt is supplied —
    # suppress it for this constructor smoke check.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        sg = ALGORITHM_DISPATCH["semguard"]()
    assert isinstance(sg, SemGuardEvaluatorProcessor)

    # Unknown algorithm raises KeyError on direct lookup.
    with pytest.raises(KeyError):
        ALGORITHM_DISPATCH["nonsense"]()


# ─── test_switching_backend_mid_session_releases_old_backend_resources ─


@pytest.mark.asyncio
async def test_switching_backend_mid_session_releases_old_backend_resources_mocked():
    """Mocked variant: build a VllmBackend, replace its engine with a mock,
    call close() — assert the engine reference is cleared and a second
    warmup() builds a fresh engine.

    This catches a bug class where close() forgets to null out _engine, so
    subsequent set_prompt() / next() calls still hit the old (now invalid)
    engine handle.
    """
    from soundcode.vllm_backend import VllmBackend

    backend = VllmBackend(model="dummy", config=GenerationConfig())
    # Inject a mock engine that satisfies the close() / shutdown() contract.
    mock_engine_first = MagicMock(name="engine_first")
    mock_engine_first.shutdown = MagicMock(return_value=None)
    backend._engine = mock_engine_first
    assert backend._engine is mock_engine_first

    await backend.close()
    # close() must drop the reference so subsequent warmup() rebuilds.
    assert backend._engine is None
    # And shutdown() must have been called on the old engine.
    mock_engine_first.shutdown.assert_called_once()

    # Stub _build_engine to inject a second distinct mock so we can verify
    # the rebuild actually allocates fresh state, not reuses the old.
    mock_engine_second = MagicMock(name="engine_second")
    mock_engine_second.shutdown = MagicMock(return_value=None)

    def _stub_build():
        backend._engine = mock_engine_second

    backend._build_engine = _stub_build
    await backend.warmup()
    assert backend._engine is mock_engine_second
    assert backend._engine is not mock_engine_first

    # Final close to leave the test environment clean.
    await backend.close()
    assert backend._engine is None


@pytest.mark.asyncio
async def test_close_is_idempotent_and_warmup_after_close_works_mocked():
    """close() twice in a row must not raise. warmup() after close() must
    rebuild the engine. Catches state machine bugs where the second close()
    re-runs shutdown() on a None engine and crashes."""
    from soundcode.vllm_backend import VllmBackend

    backend = VllmBackend(model="dummy", config=GenerationConfig())
    # First close — engine is already None.
    await backend.close()
    assert backend._engine is None
    # Second close — should also be a no-op.
    await backend.close()
    assert backend._engine is None

    # Now warmup() with a stubbed build — should populate _engine.
    built = MagicMock(name="freshly_built")
    built.shutdown = MagicMock(return_value=None)

    def _stub():
        backend._engine = built

    backend._build_engine = _stub
    await backend.warmup()
    assert backend._engine is built
    # Idempotent: a second warmup must NOT rebuild.
    built_calls = [0]

    def _stub_again():
        built_calls[0] += 1
        backend._engine = built

    backend._build_engine = _stub_again
    await backend.warmup()
    assert built_calls[0] == 0, (
        "second warmup() rebuilt the engine — must be a no-op when _engine is set"
    )

    await backend.close()


# ─── slow+gpu: real load/unload swap ─────────────────────────────────


@pytest.mark.slow
@pytest.mark.gpu
@gpu_required
@pytest.mark.asyncio
async def test_switching_backend_mid_session_real_load_and_reload():
    """Real-load variant: build a VllmBackend, load weights, close, then
    build a SECOND backend with the same model — both must succeed without
    GPU-state collision. This is the "user switches backend in the UI then
    switches back" scenario."""
    from soundcode.vllm_backend import VllmBackend

    cfg = GenerationConfig(max_tokens=8)
    backend1 = VllmBackend(
        model=TEST_MODEL, config=cfg,
        gpu_memory_utilization=0.20, max_model_len=512,
    )
    try:
        await backend1.warmup()
        backend1.set_prompt("fn add(a: i32, b: i32) -> i32 {")
        tok = await backend1.next()
        assert tok.text is not None
    finally:
        await backend1.close()
    await asyncio.sleep(2.0)

    # Second backend on the same model — must work cleanly.
    backend2 = VllmBackend(
        model=TEST_MODEL, config=cfg,
        gpu_memory_utilization=0.20, max_model_len=512,
    )
    try:
        await backend2.warmup()
        backend2.set_prompt("fn sub(a: i32, b: i32) -> i32 {")
        tok2 = await backend2.next()
        assert tok2.text is not None
    finally:
        await backend2.close()


# ─── DemoClient end-to-end on a mocked vLLM backend ────────────────────


class _StubVllmBackend:
    """Implements the VllmBackend public surface DemoClient consumes; never
    touches a real engine. Used to verify DemoClient drives both backends
    identically without paying the GPU cost.

    Behavior matches `FakeLlm` in test_demo_client.py — stream a fixed list
    of tokens once per set_prompt() call."""

    def __init__(self, tokens: list[str]):
        self._tokens = list(tokens)
        self._pos = 0
        self._exhausted = False
        self.config = GenerationConfig(mode=OrchestrationMode.RAW)
        self.think_budget_exceeded = False
        self.logits_processor = NoopLogitsProcessor()

    def set_prompt(self, prompt: str) -> None:
        self._prompt = prompt
        self._exhausted = False
        self._pos = 0

    def has_next(self) -> bool:
        return not self._exhausted

    async def next(self) -> Token:
        if self._pos >= len(self._tokens):
            self._exhausted = True
            return Token("", "code")
        t = self._tokens[self._pos]
        self._pos += 1
        return Token(t, "code")

    async def abort_current_stream(self) -> None:
        self._exhausted = True

    async def warmup(self) -> None:
        pass

    async def close(self) -> None:
        pass

    async def stream_thinking_phase(self, prompt: str):
        return
        yield  # pragma: no cover


@pytest.mark.asyncio
async def test_demo_client_drives_stub_vllm_backend_to_completion():
    """End-to-end: a vLLM-shaped backend stub running through DemoClient's
    generate() loop must produce the same event types the LlmServer path
    produces — token_emitted, status, final. Catches surface-mismatch bugs
    between the two backends."""
    backend = _StubVllmBackend(["    let x = 1;\n", "\n}"])
    events: list[dict] = []
    demo = DemoClient(
        llm=backend, checker=_FakeChecker(),
        config=DemoConfig(token_delay_s=0, repetition_window=0,
                          wall_budget_s=5, max_continuations=0),
        emit=lambda ev: events.append(ev) or asyncio.sleep(0),
    )
    await demo.generate("fn f() -> i32 {")
    event_types = {e["type"] for e in events}
    assert "token_emitted" in event_types
    assert "status" in event_types
    assert "final" in event_types
    # The body-close status must appear because the second stub token closes
    # the function — same termination path the real LM hits.
    statuses = [e.get("message", "") for e in events if e["type"] == "status"]
    assert any("function body closed" in m for m in statuses), statuses


# ─── make sure the dispatch tables are stable for the round trip ───────


def test_backend_dispatch_table_keys_are_exactly_ollama_and_vllm():
    """Regression guard: if a new backend is added, this test must be
    updated. Avoids silent failures where a new key has no test coverage."""
    from soundcode.web.server import BACKEND_DISPATCH

    assert set(BACKEND_DISPATCH.keys()) == {"ollama", "vllm"}


def test_algorithm_dispatch_table_keys_are_exactly_five():
    """Regression guard: ALGORITHM_DISPATCH must cover the five known
    algorithm entries. Adding a sixth means this test (and the README) need
    updating.

    Five entries:
      - `soundcode`        — no-op (rollback via prompt re-decode)
      - `rocode`           — alias for `rocode_lite` (back-compat)
      - `rocode_lite`      — MVP flat-list decayed-penalty processor
      - `rocode_faithful`  — paper-faithful trie-backed processor
      - `semguard`         — placeholder fallback for the SemGuard
                             evaluator (real wiring uses the singleton
                             constructed in `_run_generation`)"""
    from soundcode.web.server import ALGORITHM_DISPATCH

    assert set(ALGORITHM_DISPATCH.keys()) == {
        "soundcode", "rocode", "rocode_lite", "rocode_faithful", "semguard",
    }
